sudo: required
dist: trusty
language: bash

services:
  - docker

cache:
  directories:
  # travis will keep persistent cache across builds
  - "$HOME/.ivy2"

before_install:
  - sudo pip install envtpl
  - envtpl < .m2.xml > "$HOME/.m2/settings.xml"
  - envtpl < publish.sh_template > "$HOME/publish.sh"

script:
  - >
    if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      travis_wait 60 make publish-nexus;
    else
      travis_wait 60 make test;
    fi
